# alacrittyのセッティングでは~は使えない
# ~はシェルのエイリアスである
# working_directory = "~/"

[colors.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xFFFFFF"
yellow = "0xfeff00"

[colors.cursor]
cursor = "0xffffff"
text = "0xF81CE5"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xd0d0d0"
yellow = "0xfeff00"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "Copy"
mods = "Shift"
mouse = "Left"

[[mouse.bindings]]
action = "Paste"
mods = "Shift"
mouse = "Right"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Control"


[selection]
save_to_clipboard = true

[terminal.shell]
program = "C:\\Users\\user\\.cargo\\bin\\nu.exe"

[window]
opacity = 0.95
