[helpers]

[default]
depends = []

[default.files]
"alacritty/alacritty.toml" = { target = "~/AppData/Roaming/alacritty/alacritty.toml", type = "symbolic" }

"nushell/config.nu" = { target = "~/AppData/Roaming/nushell/config.nu", type = "symbolic" }
"nushell/env.nu" = { target = "~/AppData/Roaming/nushell/env.nu", type = "symbolic" }

"wezterm/wezterm.lua" = { target = "~/.config/wezterm/wezterm.lua", type = "symbolic" }


[default.variables]
