[helpers]

[default]
depends = []

[default.files]
"alacritty/alacritty.toml" = { target = "~/AppData/Roaming/alacritty/alacritty.toml", type = "symbolic" }

"nushell/config.nu" = { target = "~/AppData/Roaming/nushell/config.nu", type = "symbolic" }
"nushell/env.nu" = { target = "~/AppData/Roaming/nushell/env.nu", type = "symbolic" }

"wezterm/wezterm.lua" = { target = "~/.config/wezterm/wezterm.lua", type = "symbolic" }


"starship/starship.toml" = { target = "~/.config/starship.toml", type = "symbolic" }

"WindowsTerminal/settings.json" = { target = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json", type = "symbolic" }
"WindowsTerminal/state.json" = { target = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/state.json", type = "symbolic" }

[default.variables]
